name: Deploy Demo

on:
  repository_dispatch:
    types: [update-build]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout demo repo
        uses: actions/checkout@v3

      - name: Checkout main project build
        uses: actions/checkout@v3
        with:
          repository: 0Arty/flow-landing-page
          path: temp-main
          token: ${{ secrets.MAIN_REPO_TOKEN }}

      - name: Copy build files
        run: |
          rm -rf *
          cp -r temp-main/build/* .
          rm -rf temp-main

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update from main repo" || echo "No changes"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./